repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
        args: ['--allow-multiple-documents']
      - id: check-added-large-files
        args: ['--maxkb=1000']
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: check-executables-have-shebangs
      - id: check-shebang-scripts-are-executable
      - id: detect-private-key

  - repo: https://github.com/psf/black
    rev: 23.12.0
    hooks:
      - id: black
        language_version: python3
        args: [--line-length=88]

  - repo: https://github.com/PyCQA/flake8
    rev: 6.1.0
    hooks:
      - id: flake8
        args: [--max-line-length=88, --extend-ignore=E203,W503]

  - repo: https://github.com/shellcheck-py/shellcheck-py
    rev: v0.9.0.6
    hooks:
      - id: shellcheck
        args: [-x]

  - repo: https://github.com/adrienverge/yamllint
    rev: v1.33.0
    hooks:
      - id: yamllint
        args: [-d, relaxed]

  - repo: local
    hooks:
      - id: check-conda-env
        name: Check conda environment file
        entry: python
        language: system
        files: '^environment\.yml$'
        args: [-c, "import yaml; yaml.safe_load(open('environment.yml'))"]
        pass_filenames: false

      - id: validate-config
        name: Validate pipeline configuration
        entry: python
        language: system
        files: '^config/.*\.yaml$'
        args: [-c, "import yaml; [yaml.safe_load(open(f)) for f in ['config/config.yaml', 'config/cluster.yaml']]"]
        pass_filenames: false