name: wes-analysis
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  # Quality control tools
  - fastqc>=0.12.1
  - multiqc>=1.24

  # Alignment and processing tools
  - bwa>=0.7.17
  - samtools>=1.19
  - picard>=3.1.1

  # Variant calling tools
  - gatk4>=4.5.0

  # Annotation tools
  - snpeff>=5.2
  - bcftools>=1.19

  # Workflow management
  - snakemake-minimal>=8.0

  # Utility tools
  - htslib>=1.19  # includes tabix and bgzip

  # Python dependencies
  - python>=3.9,<3.12
  - pandas>=2.1.0
  - numpy>=1.24.0
  - matplotlib>=3.8.0
  - seaborn>=0.13.0
  - jupyter>=1.0.0

  # Development and quality tools
  - black>=23.0.0
  - pre-commit>=3.6.0

  # Additional utilities
  - wget
  - curl
  - gzip

  # GLnexus for DeepVariant joint calling (optional - may not be available in all environments)
  # - glnexus>=1.4.1  # Uncomment if available in your conda channels

  # Note: DeepVariant is best run via its official Docker/Singularity container
  # and is not included in this central environment file.
  # It will be handled by the pipeline scripts directly.