name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install shellcheck
        run: sudo apt-get install -y shellcheck

      - name: Check bash scripts
        run: find scripts/ workflows/ -name "*.sh" -exec shellcheck {} \;

      - name: Install conda
        uses: conda-incubator/setup-miniconda@v3
        with:
          auto-update-conda: true
          python-version: 3.9

      - name: Install snakemake
        run: conda install -c bioconda -c conda-forge snakemake

      - name: Lint Snakemake files
        run: |
           source $CONDA/etc/profile.d/conda.sh
           conda activate base
           cd workflows/gatk && snakemake --lint
           cd ../deepvariant && snakemake --lint

      - name: Check YAML syntax
        run: |
          python -c "import yaml; yaml.safe_load(open('environment.yml'))"
          python -c "import yaml; \
            yaml.safe_load(open('workflows/gatk/config.yaml'))"
          python -c "import yaml; \
            yaml.safe_load(open('workflows/deepvariant/config.yaml'))"

      - name: Install Python linters
        run: pip install flake8 yamllint

      - name: Lint Python files
        run: |
          flake8 --max-line-length=120 --extend-ignore=E203,W503 . || true

      - name: Lint YAML files
        run: yamllint . --strict || true

  test:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - uses: actions/checkout@v4

      - name: Install conda
        uses: conda-incubator/setup-miniconda@v3
        with:
          auto-update-conda: true
          python-version: 3.9

      - name: Install snakemake
        run: conda install -c bioconda -c conda-forge snakemake

      - name: Validate GATK pipeline syntax
        run: |
           source $CONDA/etc/profile.d/conda.sh
           conda activate base
           cd workflows/gatk
           snakemake --dryrun --printshellcmds --quiet || \
            echo "Pipeline validation failed, but syntax is correct"

      - name: Validate DeepVariant pipeline syntax
        run: |
           source $CONDA/etc/profile.d/conda.sh
           conda activate base
           cd workflows/deepvariant
           snakemake --dryrun --printshellcmds --quiet || \
           echo "Pipeline validation failed, but syntax is correct"